MINOR : early catch keepass password validity

diff --git a/local/scripts/upgradeAll b/local/scripts/upgradeAll
--- a/local/scripts/upgradeAll
+++ b/local/scripts/upgradeAll
@@ -8,6 +8,11 @@ echo -n "Enter KeePassXC database password: "
 read -s KP_PASSWORD
 echo
  
+# Get identities, exit early if it fails
+if ! ssh-add-ansible-identities.sh $KP_PASSWORD --dry-run; then
+    exit 1
+fi
+
 # AUR updates
 yay -Syu;
  
